// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./components/Content.vue')['default']
    ContentItem: typeof import('./components/ContentItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Quote: typeof import('./components/Quote.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}

export { }
