name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  setup:
    name: setup envrioment and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.15.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: install
        run: pnpm install

      - name: build
        run: pnpm build
